const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');
const { generateDesk } = require('./desk-generator');
const { fillLoginForm } = require('./auto-login');
const sharp = require('sharp');

/**
 * Hapus watermark "Generated by CekSkin · cekskin.com" di footer kiri-bawah poster.
 * Caranya: salin patch background bersih dari tengah footer (area kosong antara
 * teks kiri & kanan) lalu timpa ke area watermark — hasil match sempurna tanpa seam.
 * Stats kanan ("X Rare Skins ...") sengaja dibiarkan (bukan branding).
 * @param {string} filePath - path poster yang akan diproses (ditimpa di tempat).
 */
async function removeWatermark(filePath) {
  const m = await sharp(filePath).metadata();
  const W = m.width, H = m.height;
  const patchW = Math.min(560, Math.round(W * 0.30));
  const patchH = 64;
  const patchTop = H - patchH;
  const patchLeft = Math.round(W / 2 - patchW / 2); // tengah footer = area kosong
  const patch = await sharp(filePath)
    .extract({ left: patchLeft, top: patchTop, width: patchW, height: patchH })
    .toBuffer();
  const out = await sharp(filePath)
    .composite([{ input: patch, left: 0, top: patchTop }]) // timpa watermark kiri
    .jpeg({ quality: 92 })
    .toBuffer();
  fs.writeFileSync(filePath, out);
}

// Browser persisten (warm) — dibiarkan hidup antar panggilan /cekskin biar tidak
// bayar cold-start Playwright (~1-2 dtk) tiap kali. Context tetap dibuat & ditutup
// per-panggilan (sesi bersih). Relaunch otomatis kalau browser mati/crash.
let sharedBrowser = null;
async function getBrowser() {
  if (sharedBrowser && sharedBrowser.isConnected()) return sharedBrowser;
  sharedBrowser = await chromium.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--disable-gpu'],
  });
  return sharedBrowser;
}

/**
 * Fungsi untuk menjalankan automasi CekSkin
 * @param {string} gameId - ID Game MLBB
 * @returns {Promise<{posterPath: string, descriptionText: string}>}
 */
async function checkSkin(gameId) {
  const statePath = path.join(__dirname, 'state.json');
  if (!fs.existsSync(statePath)) {
    throw new Error('state.json tidak ditemukan! Bot belum login ke CekSkin.');
  }

  const browser = await getBrowser();
  const context = await browser.newContext({ storageState: statePath });
  const page = await context.newPage();
  page.setDefaultTimeout(20000);

  // Promise yang resolve begitu data skin masuk (biar tidak polling lambat).
  let resolveSkins;
  const skinsReady = new Promise((r) => { resolveSkins = r; });

  let skinsData = null;
  let lookupData = null;
  let playerName = 'Unknown';
  console.log('[checkSkin] Memulai proses untuk gameId:', gameId);

  page.on('response', async (response) => {
    const url = response.url();
    if (url.includes('/api/players/') && url.endsWith('/skins') && response.status() === 200) {
      try {
        skinsData = await response.json();
        resolveSkins();
      } catch (err) {}
    }
    if (url.includes('/api/players/') && url.includes('/lookup') && response.status() === 200) {
      try {
        lookupData = await response.json();
      } catch (err) {}
    }
  });

  // Satu kali percobaan pencarian: isi ID → Cari Skin → tunggu MODAL OKE atau
  // FORM LOGIN muncul. Return 'OK' kalau lanjut ke gallery, 'NEED_LOGIN' kalau
  // ternyata sesi expired (muncul form email login).
  async function attemptSearch() {
    console.log('[checkSkin] Navigasi ke cekskin.com');
    await page.goto('https://cekskin.com', { waitUntil: 'domcontentloaded' });

    // PENTING: cekskin React SPA sempat render kondisi "logged-out" sesaat saat
    // hydrate. Kalau langsung isi ID + klik Cari Skin, bot bisa salah kira sesi
    // expired (race). Jadi tunggu dulu auth settle: tombol "Keluar" (logout) di
    // header = sesi login sudah dikenali. Kalau memang expired, "Keluar" tidak
    // muncul (timeout 8 dtk) dan attemptSearch lanjut → form login terdeteksi wajar.
    await page.getByText(/Keluar/i).first().waitFor({ timeout: 8000 }).catch(() => {});

    console.log('[checkSkin] Mengisi ID game');
    const idInput = page.getByPlaceholder(/ID/i).first();
    await idInput.waitFor({ timeout: 15000 });
    await idInput.fill(gameId.toString());

    console.log('[checkSkin] Klik tombol Cari Skin');
    await page.getByRole('button', { name: /Cari Skin/i }).first().click();

    // Tunggu salah satu muncul: tombol "Oke" (sesi valid) atau form Email (sesi expired)
    const btnOke = page.getByRole('button', { name: /Oke/i }).first();
    const emailField = page.getByPlaceholder(/Email/i).first();
    await Promise.race([
      btnOke.waitFor({ timeout: 15000 }).catch(() => {}),
      emailField.waitFor({ timeout: 15000 }).catch(() => {}),
    ]);

    if (await emailField.count() > 0) {
      return 'NEED_LOGIN';
    }

    console.log('[checkSkin] Klik tombol Oke');
    await btnOke.click();

    console.log('[checkSkin] Menunggu navigasi ke gallery...');
    await page.waitForURL('**/gallery?q=**', { timeout: 30000 });
    return 'OK';
  }

  try {
    let searchResult = await attemptSearch();

    // Auto-recovery: kalau sesi expired, login otomatis (pakai kredensial di
    // auto-login.js), simpan sesi baru, lalu ulangi pencarian sekali.
    if (searchResult === 'NEED_LOGIN') {
      console.log('[checkSkin] Terdeteksi butuh login — menjalankan auto-login...');
      try {
        await fillLoginForm(page);
        await context.storageState({ path: statePath }); // simpan sesi baru untuk run berikutnya
        console.log('[checkSkin] Auto-login berhasil, state.json diperbarui.');
      } catch (e) {
        // Kemungkinan false-positive (race saat hydrate) — form login sudah hilang.
        // Jangan menyerah; cukup ulangi pencarian, auth harusnya sudah settle.
        console.log('[checkSkin] Login dilewati (' + e.message + '). Mengulang pencarian...');
      }
      searchResult = await attemptSearch();
      if (searchResult === 'NEED_LOGIN') {
        throw new Error('Auto-login gagal — sesi tetap tidak valid. Cek kredensial cekskin.');
      }
    }

    console.log('[checkSkin] Menunggu data skin (API)...');
    // Resolve segera begitu response /skins masuk; cap 15 dtk kalau lambat.
    if (!skinsData) {
      await Promise.race([
        skinsReady,
        new Promise((r) => setTimeout(r, 15000)),
      ]);
    }

    if (!skinsData) {
      throw new Error('Gagal mendapatkan data skins dari CekSkin.');
    }

    // Nickname: utamakan dari response /lookup, fallback ke header halaman
    if (lookupData && lookupData.nickname) {
      playerName = lookupData.nickname;
    } else {
      try {
        const headerText = await page.locator('h1, h2, h3').first().innerText();
        playerName = headerText.split('\n')[0].trim();
      } catch(e) {}
    }

    // Scrape gelar collector (mis. "Mega Collector 4") langsung dari DOM gallery.
    // DOM kadang telat render setelah data masuk, jadi retry beberapa kali.
    let collectorTitle = '';
    for (let i = 0; i < 6; i++) {
      try {
        collectorTitle = await page.evaluate(() => {
          for (const el of document.querySelectorAll('span')) {
            const t = el.textContent.trim();
            if (/collector\s*\d/i.test(t) && !t.includes('·')) return t;
          }
          return '';
        });
      } catch(e) {}
      if (collectorTitle) break;
      await page.waitForTimeout(350);
    }
    console.log('[checkSkin] Nickname:', playerName, '| Collector:', collectorTitle);

    const deskResult = generateDesk(skinsData, { nickname: playerName, collectorTitle });
    let totalRare = deskResult.totalRare;
    if (totalRare === 0) totalRare = 1;

    console.log('[checkSkin] Navigasi ke poster...');
    const currentUrl = new URL(page.url());
    const token = currentUrl.searchParams.get('q');
    await page.goto(`https://cekskin.com/poster?q=${token}`, { waitUntil: 'domcontentloaded' });
    await page.locator('input[type="range"]').first().waitFor({ timeout: 15000 });

    console.log('[checkSkin] Mengatur slider ke', totalRare, 'skin...');
    // Slider "Jumlah Skin di Poster" adalah React controlled input — `node.value = x`
    // biasa diabaikan React (poster stuck di default 24). Harus pakai native value
    // setter supaya state React ikut ter-update.
    await page.evaluate((val) => {
      const setter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;
      document.querySelectorAll('input[type="range"]').forEach(node => {
        const max = Number(node.max) || val;
        const finalVal = Math.min(val, max);
        setter.call(node, String(finalVal));
        node.dispatchEvent(new Event('input', { bubbles: true }));
        node.dispatchEvent(new Event('change', { bubbles: true }));
      });
    }, totalRare);

    try {
      console.log('[checkSkin] Mencari input judul poster...');
      const inputElement = page.getByLabel(/JUDUL POSTER/i).or(page.getByPlaceholder(/Judul/i)).first();
      await inputElement.fill('Jago Game', { timeout: 5000 });
      console.log('[checkSkin] Judul poster diisi (primary).');
    } catch (e) {
      console.log('[checkSkin] Fallback mencari input text...');
      const textInputs = page.locator('input[type="text"]');
      const count = await textInputs.count();
      for (let i = 0; i < count; i++) {
        const val = await textInputs.nth(i).inputValue({ timeout: 2000 }).catch(() => '');
        if (val.toUpperCase().includes('AKUN MLBB') || val.toUpperCase().includes('DIJUAL')) {
          await textInputs.nth(i).fill('Jago Game', { timeout: 2000 });
          console.log('[checkSkin] Judul poster diisi (fallback).');
          break;
        }
      }
    }

    console.log('[checkSkin] Klik tombol Preview...');
    const btnPreview = page.getByRole('button', { name: /Lihat Preview/i }).first();
    if (await btnPreview.count() > 0) {
      await btnPreview.click();
    }
    
    console.log('[checkSkin] Menunggu render preview...');
    // networkidle = semua gambar skin sudah termuat dari network (gate andal biar
    // render HD tidak gagal). Buang fixed delay 3 dtk lama; cukup buffer kecil.
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(600);

    console.log('[checkSkin] Klik tombol Download Poster...');
    const btnDownload = page.getByRole('button', { name: /Download Poster/i }).first();
    
    const [download] = await Promise.all([
      page.waitForEvent('download', { timeout: 30000 }), // render HD kadang lama
      btnDownload.click()
    ]);

    console.log('[checkSkin] Download event tertangkap. Menyimpan file...');
    const safeNickname = playerName.replace(/[^a-z0-9]/gi, '_');
    const fileName = `${gameId} - ${safeNickname} - Jago Game.jpg`;
    
    const outputDir = path.join(__dirname, 'output');
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir);
    }
    
    const outputPath = path.join(outputDir, fileName);
    await download.saveAs(outputPath);

    // Hapus watermark "Generated by CekSkin · cekskin.com" (pojok kiri bawah) —
    // tidak boleh ada branding pihak lain pas upload ke marketplace.
    try {
      await removeWatermark(outputPath);
      console.log('[checkSkin] Watermark cekskin dihapus.');
    } catch (e) {
      console.log('[checkSkin] Gagal hapus watermark (lanjut pakai poster asli):', e.message);
    }

    return {
      posterPath: outputPath,
      descriptionText: deskResult.text,
      playerName: playerName
    };

  } catch (error) {
    try {
        await page.screenshot({ path: path.join(__dirname, 'error_debug.png'), fullPage: true });
    } catch (e) {}
    throw error;
  } finally {
    // Tutup context saja — browser dibiarkan warm untuk panggilan berikutnya.
    try { await context.close(); } catch (e) {}
  }
}

async function closeBrowser() {
  if (sharedBrowser) {
    try { await sharedBrowser.close(); } catch (e) {}
    sharedBrowser = null;
  }
}

module.exports = { checkSkin, closeBrowser };

// Jika dijalankan langsung dari terminal: node index.js 123456
if (require.main === module) {
  const arg = process.argv[2];
  if (!arg) {
    console.log('Cara Penggunaan: node index.js <GameID>');
    process.exit(1);
  }
  checkSkin(arg).then(async res => {
    console.log('=== SUKSES ===');
    console.log('Poster Tersimpan di:', res.posterPath);
    console.log('\n--- DESKRIPSI ---');
    console.log(res.descriptionText);
    await closeBrowser(); // tutup browser persisten di mode CLI biar tidak orphan
    process.exit(0);
  }).catch(async err => {
    console.error('Error:', err.message);
    await closeBrowser();
    process.exit(1);
  });
}
